apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-main-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server-main
  template:
    metadata:
      labels:
        component: server-main
    spec:
      containers:
        - name: server-main
          image: prashantdey/completeprojectb14:servermainv1.0
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SERVER_MAIN_PORT
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PGHOST
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PGPORT
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PGDATABASE
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PGUSER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PGPASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
