apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: stats-service
  template:
    metadata:
      labels:
        component: stats-service
    spec:
      containers:
        - name: stats-service
          image: prashantdey/completeprojectb14:statsservicev1.0
          ports:
            - containerPort: 50053
          env:
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PGHOST
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PGPORT
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PGDATABASE
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PGUSER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PGPASSWORD
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
